version: '3.8'
services:
  db:
    build: .
    container_name: vec_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: great
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
