version: "3.8"

services:
  postgres:
    build:
      context: . # Path to your Dockerfile
      dockerfile: _Dockerfile # Name of the Dockerfile
    container_name: pt_vec_db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: good
      POSTGRES_DB: vector_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
